[package]
name = "tower_of_hanoi"
version = "0.1.0"
authors = ["Amanda Koh <amanda@naucera.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
